name: Metrics
on:
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:
  push:
    branches:
      - output
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics 1
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics1.svg
          user: sapphi-red
          base: header, activity, repositories, metadata
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          repositories_skipped: piscon2019,piscon2019-2,go-traq
          use_prebuilt_image: yes

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%

          plugin_lines: yes

          plugin_notable: yes
          plugin_notable_filter: stars:>100
          plugin_notable_from: organization
          plugin_notable_indepth: yes

          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://green.sapphi.red/feed.rss


      - name: Generate GitHub Contribution Grid Pac-Man
        uses: abozanona/pacman-contribution-graph@main
        continue-on-error: true
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.METRICS_TOKEN }}
          
      - name: Copy GitHub Contribution Grid Pac-Man to .github/images
        if: always()
        run: |
          mkdir -p .github/workflows
          # Light version
          if [ -f dist/pacman-contribution-graph.svg ]; then
            cp -v dist/pacman-contribution-graph.svg .github/workflows/github-contribution-grid-pacman.svg
          fi
          # Dark version
          if [ -f dist/pacman-contribution-graph-dark.svg ]; then
            cp -v dist/pacman-contribution-graph-dark.svg .github/workflows/github-contribution-grid-pacman-dark.svg
          fi


          
